' ******************************************************************************
' swxJRNL.swj - journal recorded on 04/12/20 by simmetm
' *****************************************************************************
Dim swApp As Object

Dim Part As Object
Dim boolstatus As Boolean
Dim longstatus As Long, longwarnings As Long

Sub main()

Set swApp = Application.SldWorks

swApp.ActivateDoc2 "Full_Assembly.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
boolstatus = Part.ShowConfiguration2("HBOLT 0.4375-20x1.375x1.125-N")
boolstatus = Part.ShowConfiguration2("Preferred Wide FW 0.4375")
boolstatus = Part.ShowConfiguration2("HTNUT 0.4375-14-D-N")
boolstatus = Part.ShowConfiguration2("HBOLT 0.3125-18x1.375x0.875-N")
boolstatus = Part.ShowConfiguration2("Preferred Narrow FW 0.3125")
boolstatus = Part.ShowConfiguration2("HTNUT 0.3125-18-D-N")
boolstatus = Part.ShowConfiguration2("HBOLT 0.5000-13x1.375x1.25-N")
boolstatus = Part.ShowConfiguration2("Preferred Wide FW 0.5")
boolstatus = Part.ShowConfiguration2("Internal Tooth LW Type A-0.3125")
Set Part = swApp.ActiveDoc
Dim myModelView As Object
Set myModelView = Part.ActiveView
myModelView.FrameLeft = 0
myModelView.FrameTop = 22
Set myModelView = Part.ActiveView
myModelView.FrameWidth = 1525
myModelView.FrameHeight = 702
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03058371656143713327, -0.05090543651650138862, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03495281892735671581, -0.05090543651650138862, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03058371656143713327, -0.07126761112310195379, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03495281892735671581, -0.07126761112310195379, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0174764094636783579, -0.03054326190990083387, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0480601260251154877, -0.05090543651650138862, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, 0, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0.08144869842640221902, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.1934406587627052754, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, 0.1425352222462039076, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, 0.1018108730330027772, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, 0.1119919603363030564, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0480601260251154877, 0.1425352222462039076, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03058371656143713327, 0.07126761112310195379, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, 0.02036217460660055475, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, 0.02036217460660055475, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03932192129327630875, 0, 0.8865749248832912599, -0.1026791510373641358, -1.000834645465886297

' Roll View
Dim swModelView As Object
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, -0.05090543651650138862, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, -0.08144869842640221902, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, -0.06108652381980166773, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, -0.08144869842640221902, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07427474022063301762, -0.1832595714594049963, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03932192129327630875, -0.03054326190990083387, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0436910236591959017, 0, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1004893544161505753, 0.04072434921320110951, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0786438425865526175, 0.06108652381980166773, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0480601260251154877, 0.09162978572970249813, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03932192129327630875, 0.1018108730330027772, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03058371656143713327, 0.06108652381980166773, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03495281892735671581, 0.07126761112310195379, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, 0.02036217460660055475, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.08738204731839180339, -0.1527163095495041867, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.08301294495247220351, -0.1527163095495041867, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.1267039686116681052, -0.1323541349429036285, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.1835022993686227788, -0.02036217460660055475, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0961202520502309754, 0.01018108730330027738, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, 0.01018108730330027738, -0.2103250350630219145, 0.2935482018369270918, -0.5014228718478648261

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.166025889904944407, 0.09162978572970249813, 0.6469348797572251897, 0.2050757289873104128, -0.5699949881413601815
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06990563785471343161, 0.01018108730330027738, 0.6469348797572251897, 0.2050757289873104128, -0.5699949881413601815
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06116743312287426654, 0.01018108730330027738, 0.6469348797572251897, 0.2050757289873104128, -0.5699949881413601815
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0480601260251154877, 0.02036217460660055475, 0.6469348797572251897, 0.2050757289873104128, -0.5699949881413601815
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03495281892735671581, 0, 0.6469348797572251897, 0.2050757289873104128, -0.5699949881413601815
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02184551182959795085, 0.02036217460660055475, 0.6469348797572251897, 0.2050757289873104128, -0.5699949881413601815
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0174764094636783579, 0.02036217460660055475, 0.6469348797572251897, 0.2050757289873104128, -0.5699949881413601815
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0, 0.6469348797572251897, 0.2050757289873104128, -0.5699949881413601815
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.08738204731839180339, -0.01018108730330027738, 0.6469348797572251897, 0.2050757289873104128, -0.5699949881413601815
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1223348662457485331, -0.06108652381980166773, 0.6469348797572251897, 0.2050757289873104128, -0.5699949881413601815
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1135966615139093333, -0.04072434921320110951, 0.6469348797572251897, 0.2050757289873104128, -0.5699949881413601815
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05242922839103508065, -0.01018108730330027738, 0.6469348797572251897, 0.2050757289873104128, -0.5699949881413601815
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0436910236591959017, 0.01018108730330027738, 0.6469348797572251897, 0.2050757289873104128, -0.5699949881413601815

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, -0.04072434921320110951, 0.6719449248833484489, 0.01799216819568982828, -0.444260264230052826
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06116743312287426654, -0.1119919603363030564, 0.6719449248833484489, 0.01799216819568982828, -0.444260264230052826
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0480601260251154877, -0.06108652381980166773, 0.6719449248833484489, 0.01799216819568982828, -0.444260264230052826
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03058371656143713327, -0.03054326190990083387, 0.6719449248833484489, 0.01799216819568982828, -0.444260264230052826
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0436910236591959017, -0.06108652381980166773, 0.6719449248833484489, 0.01799216819568982828, -0.444260264230052826
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02621461419551754032, -0.05090543651650138862, 0.6719449248833484489, 0.01799216819568982828, -0.444260264230052826
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03495281892735671581, -0.05090543651650138862, 0.6719449248833484489, 0.01799216819568982828, -0.444260264230052826
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.01018108730330027738, 0.6719449248833484489, 0.01799216819568982828, -0.444260264230052826
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0174764094636783579, 0.1119919603363030564, 0.6719449248833484489, 0.01799216819568982828, -0.444260264230052826
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06990563785471343161, 0.2647082698858072569, 0.6719449248833484489, 0.01799216819568982828, -0.444260264230052826
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06990563785471343161, 0.162897396852804438, 0.6719449248833484489, 0.01799216819568982828, -0.444260264230052826

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, -0.162897396852804438, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, -0.1323541349429036285, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, -0.09162978572970249813, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, -0.1730784841561047172, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, -0.1730784841561047172, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.1527163095495041867, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.1119919603363030564, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, -0.08144869842640221902, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, -0.05090543651650138862, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, 0, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03058371656143713327, 0, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, 0.03054326190990083387, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, 0.2036217460660055545, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.08144869842640221902, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04072434921320110951, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, 0.01018108730330027738, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0.02036217460660055475, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02621461419551754032, 0.01018108730330027738, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0174764094636783579, 0.01018108730330027738, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02184551182959795085, 0, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, 0, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, 0, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, 0, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, 0, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0174764094636783579, -0.02036217460660055475, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02184551182959795085, -0.03054326190990083387, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, -0.03054326190990083387, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, -0.02036217460660055475, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0.02036217460660055475, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, 0.2036217460660055545, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, 0.2138028333693058336, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0.08144869842640221902, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.08144869842640221902, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01018108730330027738, -0.03251772324694002236, -0.1042227674839182328, -1.308459173468619952

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.07126761112310195379, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0.1730784841561047172, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0.08144869842640221902, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0.07126761112310195379, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.07126761112310195379, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, 0.1527163095495041867, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, 0.1018108730330027772, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03495281892735671581, 0.07126761112310195379, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0436910236591959017, 0.04072434921320110951, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0786438425865526175, 0.01018108730330027738, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0436910236591959017, 0, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02621461419551754032, 0, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, 0, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03058371656143713327, -0.04072434921320110951, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0436910236591959017, -0.1018108730330027772, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, -0.07126761112310195379, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, -0.09162978572970249813, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.07126761112310195379, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.02036217460660055475, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.01018108730330027738, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, 0.01018108730330027738, 0.9621353780216281848, -0.06192794512782029415, -0.3783631782450811443

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Open
Set Part = swApp.OpenDoc6("W:\EGR107\0_NewGoKart\Big_Britney\middle chassis\Full_Assembly_2.0.SLDASM", 2, 0, "", longstatus, longwarnings)
Dim swAssembly As Object
Set swAssembly = Part
swApp.ActivateDoc2 "Full_Assembly_2.0.SLDASM", False, longstatus
Set Part = swApp.ActiveDoc
boolstatus = Part.ShowConfiguration2("TBOLT 0.3125-18x0.875x0.875-N")
boolstatus = Part.ShowConfiguration2("HBOLT 0.5000-13x1.875x1.25-N")
Set myModelView = Part.ActiveView
myModelView.FrameWidth = 1525
myModelView.FrameHeight = 702
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02184551182959795085, 0.3156137064023086247, 0.5463214609495778973, 0.08228927653601658676, 0.5686128984984861745
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0174764094636783579, 0.2138028333693058336, 0.5463214609495778973, 0.08228927653601658676, 0.5686128984984861745
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02184551182959795085, 0.2138028333693058336, 0.5463214609495778973, 0.08228927653601658676, 0.5686128984984861745
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0.1119919603363030564, 0.5463214609495778973, 0.08228927653601658676, 0.5686128984984861745
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05090543651650138862, 0.5463214609495778973, 0.08228927653601658676, 0.5686128984984861745
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.09162978572970249813, 0.5463214609495778973, 0.08228927653601658676, 0.5686128984984861745
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, 0.1119919603363030564, 0.5463214609495778973, 0.08228927653601658676, 0.5686128984984861745
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, 0.1018108730330027772, 0.5463214609495778973, 0.08228927653601658676, 0.5686128984984861745
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0.04072434921320110951, 0.5463214609495778973, 0.08228927653601658676, 0.5686128984984861745
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02036217460660055475, 0.5463214609495778973, 0.08228927653601658676, 0.5686128984984861745

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0480601260251154877, -0.1018108730330027772, 0.5394438480831809102, 0.07632642996729543938, 0.7555772275897254531
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, -0.1221730476396033355, 0.5394438480831809102, 0.07632642996729543938, 0.7555772275897254531
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, -0.09162978572970249813, 0.5394438480831809102, 0.07632642996729543938, 0.7555772275897254531
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02621461419551754032, -0.1730784841561047172, 0.5394438480831809102, 0.07632642996729543938, 0.7555772275897254531
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, -0.09162978572970249813, 0.5394438480831809102, 0.07632642996729543938, 0.7555772275897254531
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, -0.1425352222462039076, 0.5394438480831809102, 0.07632642996729543938, 0.7555772275897254531
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, -0.09162978572970249813, 0.5394438480831809102, 0.07632642996729543938, 0.7555772275897254531
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, 0.5394438480831809102, 0.07632642996729543938, 0.7555772275897254531

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0.06108652381980166773, 0.5379367735710616216, 0.1115283830905013929, 0.6562127232510306385
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04072434921320110951, 0.5379367735710616216, 0.1115283830905013929, 0.6562127232510306385
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03054326190990083387, 0.5379367735710616216, 0.1115283830905013929, 0.6562127232510306385
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.09162978572970249813, 0.5379367735710616216, 0.1115283830905013929, 0.6562127232510306385
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, 0.1832595714594049963, 0.5379367735710616216, 0.1115283830905013929, 0.6562127232510306385
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02036217460660055475, 0.5379367735710616216, 0.1115283830905013929, 0.6562127232510306385

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03932192129327630875, -0.09162978572970249813, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, -0.2952515317957080665, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.08144869842640221902, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, -0.1018108730330027772, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, -0.04072434921320110951, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, -0.05090543651650138862, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, -0.02036217460660055475, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, -0.02036217460660055475, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, -0.03054326190990083387, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.05090543651650138862, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.05090543651650138862, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, -0.02036217460660055475, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02184551182959795085, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02621461419551754032, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02184551182959795085, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, 0.01018108730330027738, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0.03054326190990083387, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, 0.07126761112310195379, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01018108730330027738, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01018108730330027738, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.06108652381980166773, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01018108730330027738, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, 0.06108652381980166773, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06990563785471343161, 0.2850704444924078151, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0436910236591959017, 0.1832595714594049963, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05679833075695466665, 0.1934406587627052754, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06116743312287426654, 0.2239839206726061127, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03932192129327630875, 0.2138028333693058336, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, 0.04072434921320110951, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.1135966615139093333, 0.1018108730330027772, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06553653548879384561, 0.09162978572970249813, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0917511496843113894, 0.1018108730330027772, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06553653548879384561, 0.03054326190990083387, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, 0.01018108730330027738, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0480601260251154877, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03495281892735671581, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03058371656143713327, -0.02036217460660055475, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0480601260251154877, -0.04072434921320110951, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0436910236591959017, -0.02036217460660055475, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.05242922839103508065, 0.04072434921320110951, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, 0.02036217460660055475, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02621461419551754032, 0.01018108730330027738, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03058371656143713327, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03932192129327630875, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, -0.02036217460660055475, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, -0.02036217460660055475, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02621461419551754032, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, -0.02036217460660055475, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.1425352222462039076, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.06108652381980166773, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.03054326190990083387, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.01018108730330027738, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, -0.02036217460660055475, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, -0.03054326190990083387, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, -0.01018108730330027738, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.09162978572970249813, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.07126761112310195379, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.04072434921320110951, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03932192129327630875, -0.07126761112310195379, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03932192129327630875, -0.01018108730330027738, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02621461419551754032, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, 0.03054326190990083387, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03495281892735671581, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06553653548879384561, -0.07126761112310195379, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05679833075695466665, -0.1018108730330027772, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05242922839103508065, -0.08144869842640221902, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.07427474022063301762, -0.08144869842640221902, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03495281892735671581, -0.03054326190990083387, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0786438425865526175, -0.06108652381980166773, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06990563785471343161, -0.04072434921320110951, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0174764094636783579, 0, 0.5391994694934396648, 0.08116749159779601541, 0.7281647194476477125

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05090543651650138862, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.08144869842640221902, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05090543651650138862, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02036217460660055475, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04072434921320110951, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.07126761112310195379, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, 0.02036217460660055475, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01018108730330027738, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, 0.01018108730330027738, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, 0.03054326190990083387, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, 0.02036217460660055475, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01018108730330027738, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02621461419551754032, 0.06108652381980166773, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03495281892735671581, 0.1221730476396033355, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, 0.07126761112310195379, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0480601260251154877, 0.08144869842640221902, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0436910236591959017, 0.08144869842640221902, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, 0.01018108730330027738, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02621461419551754032, 0.04072434921320110951, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03495281892735671581, 0.02036217460660055475, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, 0.02036217460660055475, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03495281892735671581, 0.02036217460660055475, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03932192129327630875, 0.02036217460660055475, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03932192129327630875, 0.02036217460660055475, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, 0.02036217460660055475, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07427474022063301762, 0.08144869842640221902, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03495281892735671581, 0.05090543651650138862, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0.01018108730330027738, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02036217460660055475, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.1004893544161505753, -0.3054326190990083734, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0480601260251154877, -0.09162978572970249813, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03058371656143713327, -0.05090543651650138862, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0436910236591959017, -0.08144869842640221902, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.1135966615139093333, -0.162897396852804438, 0.5379367735710616216, 0.1268441134529325609, 0.4927384746319347641

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02184551182959795085, -0.08144869842640221902, 0.3254173576230527942, 0.1082351962863867811, 1.240757183999221525
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03058371656143713327, -0.07126761112310195379, 0.3254173576230527942, 0.1082351962863867811, 1.240757183999221525
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03495281892735671581, -0.06108652381980166773, 0.3254173576230527942, 0.1082351962863867811, 1.240757183999221525
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03932192129327630875, -0.07126761112310195379, 0.3254173576230527942, 0.1082351962863867811, 1.240757183999221525
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02621461419551754032, -0.06108652381980166773, 0.3254173576230527942, 0.1082351962863867811, 1.240757183999221525
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02621461419551754032, -0.07126761112310195379, 0.3254173576230527942, 0.1082351962863867811, 1.240757183999221525
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02184551182959795085, -0.06108652381980166773, 0.3254173576230527942, 0.1082351962863867811, 1.240757183999221525
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0174764094636783579, -0.06108652381980166773, 0.3254173576230527942, 0.1082351962863867811, 1.240757183999221525
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, -0.02036217460660055475, 0.3254173576230527942, 0.1082351962863867811, 1.240757183999221525

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0, 0.2680319417680152583, 0.1082351962862730943, 1.486424311119307617
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03495281892735671581, -0.08144869842640221902, 0.2680319417680152583, 0.1082351962862730943, 1.486424311119307617

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, 0, 0.4115367735709014596, 0.201682418355687787, 1.380471115114318081
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, 0.07126761112310195379, 0.4115367735709014596, 0.201682418355687787, 1.380471115114318081
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0.03054326190990083387, 0.4115367735709014596, 0.201682418355687787, 1.380471115114318081
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, 0.04072434921320110951, 0.4115367735709014596, 0.201682418355687787, 1.380471115114318081
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0.01018108730330027738, 0.4115367735709014596, 0.201682418355687787, 1.380471115114318081
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, 0.04072434921320110951, 0.4115367735709014596, 0.201682418355687787, 1.380471115114318081
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, 0.02036217460660055475, 0.4115367735709014596, 0.201682418355687787, 1.380471115114318081
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01018108730330027738, 0.4115367735709014596, 0.201682418355687787, 1.380471115114318081

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByID2("MC-1@Full_Assembly_2.0", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0174764094636783579, 0, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05242922839103508065, 0, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.07427474022063301762, 0.01018108730330027738, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.06990563785471343161, 0.06108652381980166773, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03495281892735671581, 0.03054326190990083387, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01018108730330027738, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.07126761112310195379, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03495281892735671581, -0.3665191429188099925, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, -0.1119919603363030564, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, -0.1425352222462039076, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.09162978572970249813, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03054326190990083387, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01018108730330027738, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.1425352222462039076, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02036217460660055475, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04072434921320110951, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, 0.06108652381980166773, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0.01018108730330027738, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0.05090543651650138862, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0.04072434921320110951, 0.5379367735709479348, 0.4002569323387774602, 0.8861215451367741025

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.08738204731839180339, 0.4276056667386116672, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03058371656143713327, 0.2036217460660055545, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03495281892735671581, 0.162897396852804438, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, 0.08144869842640221902, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, 0.08144869842640221902, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, 0.06108652381980166773, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03932192129327630875, 0.04072434921320110951, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.07427474022063301762, 0.1018108730330027772, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0436910236591959017, 0.1527163095495041867, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02621461419551754032, 0.06108652381980166773, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03495281892735671581, 0.02036217460660055475, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0480601260251154877, 0.05090543651650138862, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0480601260251154877, 0.05090543651650138862, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, 0.02036217460660055475, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.03495281892735671581, 0.02036217460660055475, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, 0.01018108730330027738, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, 0, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, 0.01018108730330027738, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, 0, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.0174764094636783579, 0, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.01310730709775877016, 0, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.1018108730330027772, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, -0.1527163095495041867, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03932192129327630875, -0.1323541349429036285, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0480601260251154877, -0.1018108730330027772, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02621461419551754032, -0.06108652381980166773, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, -0.01018108730330027738, 0.5359965787815212934, 0.4870935911645517535, 0.9620676843955777713

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0174764094636783579, -0.1119919603363030564, 0.5379367735710616216, 0.193670317197870645, 0.5907140896692339993
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, -0.05090543651650138862, 0.5379367735710616216, 0.193670317197870645, 0.5907140896692339993
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, 0.5379367735710616216, 0.193670317197870645, 0.5907140896692339993
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02184551182959795085, -0.09162978572970249813, 0.5379367735710616216, 0.193670317197870645, 0.5907140896692339993
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02621461419551754032, -0.09162978572970249813, 0.5379367735710616216, 0.193670317197870645, 0.5907140896692339993
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, -0.04072434921320110951, 0.5379367735710616216, 0.193670317197870645, 0.5907140896692339993
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02184551182959795085, -0.05090543651650138862, 0.5379367735710616216, 0.193670317197870645, 0.5907140896692339993
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, -0.01018108730330027738, 0.5379367735710616216, 0.193670317197870645, 0.5907140896692339993
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, -0.06108652381980166773, 0.5379367735710616216, 0.193670317197870645, 0.5907140896692339993
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.08144869842640221902, 0.5379367735710616216, 0.193670317197870645, 0.5907140896692339993
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, 0.5379367735710616216, 0.193670317197870645, 0.5907140896692339993

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03054326190990083387, 0.5840624035216706034, 0.4265777852500036715, 1.125214337003427545
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.08144869842640221902, 0.5840624035216706034, 0.4265777852500036715, 1.125214337003427545
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02036217460660055475, 0.5840624035216706034, 0.4265777852500036715, 1.125214337003427545
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02036217460660055475, 0.5840624035216706034, 0.4265777852500036715, 1.125214337003427545
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02036217460660055475, 0.5840624035216706034, 0.4265777852500036715, 1.125214337003427545
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02036217460660055475, 0.5840624035216706034, 0.4265777852500036715, 1.125214337003427545

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02036217460660055475, -0.04405578036005408649, 0.1082351962863867811, 1.400669369162059752
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, -0.04405578036005408649, 0.1082351962863867811, 1.400669369162059752
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.03054326190990083387, -0.04405578036005408649, 0.1082351962863867811, 1.400669369162059752
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, -0.04405578036005408649, 0.1082351962863867811, 1.400669369162059752
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, -0.04405578036005408649, 0.1082351962863867811, 1.400669369162059752
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, -0.04405578036005408649, 0.1082351962863867811, 1.400669369162059752
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.03054326190990083387, -0.04405578036005408649, 0.1082351962863867811, 1.400669369162059752

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, 0, 0.1902910372995734178, 0.2755220239983486863, 1.422897305139741775
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02036217460660055475, 0.1902910372995734178, 0.2755220239983486863, 1.422897305139741775
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, -0.02036217460660055475, 0.1902910372995734178, 0.2755220239983486863, 1.422897305139741775
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, 0.1902910372995734178, 0.2755220239983486863, 1.422897305139741775
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.004369102365919589476, 0, 0.1902910372995734178, 0.2755220239983486863, 1.422897305139741775

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByID2("EA4-1@Full_Assembly_2.0/EA3-1@EA4", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("EA4-1@Full_Assembly_2.0", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("EA4-1@Full_Assembly_2.0/EA3-1@EA4", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("EA4-1@Full_Assembly_2.0", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("EA4-1@Full_Assembly_2.0/EB5-1@EA4", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Part.ClearSelection2 True
boolstatus = Part.Extension.SelectByID2("EB3-1@Full_Assembly_2.0", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
boolstatus = Part.Extension.SelectByID2("EB3-2@Full_Assembly_2.0", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.2317875583195999623
Dim swTranslation() As Double
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.314492320031735384
swTranslation(1) = 0.03862168556884248982
swTranslation(2) = 0.1212724275629871173
Dim swTranslationVar As Variant
swTranslationVar = swTranslation
Dim swMathUtils As Object
Set swMathUtils = swApp.GetMathUtility()
Dim swTranslationVector As MathVector
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.1931562985996666537
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.2687405136066929878
swTranslation(1) = 0.03218473797403536424
swTranslation(2) = 0.1010603563024893015
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.1609635821663888966
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.2306140082524911483
swTranslation(1) = 0.02682061497836279312
swTranslation(2) = 0.08421696358540774197
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.1341363184719907564
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.1988419204573228238
swTranslation(1) = 0.02235051248196895379
swTranslation(2) = 0.07018080298783979654
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.1616100222554105736
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.2042114615059222316
swTranslation(1) = 0.02786223307733870502
swTranslation(2) = 0.08455518432269859552
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.1947108701872417025
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.2106807880704998637
swTranslation(1) = 0.03450286030067573062
swTranslation(2) = 0.1018737160514440881
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.03058371656143713327, 0.1323541349429036285, 0.3726230301936084288, 0.2728386404079401473, 1.566117204812258024
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.02621461419551754032, 0.07126761112310195379, 0.3726230301936084288, 0.2728386404079401473, 1.566117204812258024
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, 0.03054326190990083387, 0.3726230301936084288, 0.2728386404079401473, 1.566117204812258024
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, -0.01018108730330027738, 0.3726230301936084288, 0.2728386404079401473, 1.566117204812258024
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06990563785471343161, -0.2239839206726061127, 0.3726230301936084288, 0.2728386404079401473, 1.566117204812258024
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, -0.08144869842640221902, 0.3726230301936084288, 0.2728386404079401473, 1.566117204812258024
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, -0.02036217460660055475, 0.3726230301936084288, 0.2728386404079401473, 1.566117204812258024

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByID2("EA4-1@Full_Assembly_2.0/flat washer type a narrow_ai-1@EA4", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, 0.06108652381980166773, 0.04260023289754144571, 0.3530604324860178167, 1.459454602947772628
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.0174764094636783579, 0.06108652381980166773, 0.04260023289754144571, 0.3530604324860178167, 1.459454602947772628
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02036217460660055475, 0.04260023289754144571, 0.3530604324860178167, 1.459454602947772628
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.02036217460660055475, 0.04260023289754144571, 0.3530604324860178167, 1.459454602947772628
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.05090543651650138862, 0.04260023289754144571, 0.3530604324860178167, 1.459454602947772628
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04072434921320110951, 0.04260023289754144571, 0.3530604324860178167, 1.459454602947772628
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.04072434921320110951, 0.04260023289754144571, 0.3530604324860178167, 1.459454602947772628
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.03054326190990083387, 0.04260023289754144571, 0.3530604324860178167, 1.459454602947772628
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01018108730330027738, 0.04260023289754144571, 0.3530604324860178167, 1.459454602947772628

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
boolstatus = Part.Extension.SelectByID2("EA4-1@Full_Assembly_2.0/EB5-1@EA4", "COMPONENT", 0, 0, 0, False, 0, Nothing, 0)
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.06116743312287426654, 0.1119919603363030564, -0.1415991167893935199, 0.1082351962864436246, 1.566207538252946563
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, 0.09162978572970249813, -0.1415991167893935199, 0.1082351962864436246, 1.566207538252946563
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.008738204731839178951, 0.09162978572970249813, -0.1415991167893935199, 0.1082351962864436246, 1.566207538252946563
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02184551182959795085, 0.09162978572970249813, -0.1415991167893935199, 0.1082351962864436246, 1.566207538252946563
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0.02621461419551754032, 0.1119919603363030564, -0.1415991167893935199, 0.1082351962864436246, 1.566207538252946563
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, 0.01018108730330027738, -0.1415991167893935199, 0.1082351962864436246, 1.566207538252946563
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02036217460660055475, -0.1415991167893935199, 0.1082351962864436246, 1.566207538252946563
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, -0.04072434921320110951, -0.1415991167893935199, 0.1082351962864436246, 1.566207538252946563
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.01310730709775877016, -0.01018108730330027738, -0.1415991167893935199, 0.1082351962864436246, 1.566207538252946563

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.2849150143227220933
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.3836597047884730549
swTranslation(1) = 0.03626014343823047437
swTranslation(2) = -0.1354082949617549658
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.3432711015936411036
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.4757012409878969561
swTranslation(1) = 0.0585444959429818404
swTranslation(2) = -0.1631425240503071861
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.2860592513280342808
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.4030812810701610571
swTranslation(1) = 0.04878707995248487972
swTranslation(2) = -0.1359521033752559838
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.2383827094400285673
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.3425646478053812061
swTranslation(1) = 0.04065589996040396698
swTranslation(2) = -0.1132934194793800003
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.1986522578666904681
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.2921341200847313302
swTranslation(1) = 0.03387991663367007078
swTranslation(2) = -0.09441118289948333131
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.2393400697189042303
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.3471758586473780994
swTranslation(1) = 0.05652575715569340548
swTranslation(2) = -0.1137484131319076441
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.2883615297818123424
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.4127271023975551678
swTranslation(1) = 0.08389480279802419282
swTranslation(2) = -0.1370462808818164735
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.3474235298576052733
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.4897517944995087857
swTranslation(1) = 0.1164450544085966349
swTranslation(2) = -0.1651160010624294905
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.4185825660935003634
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.5705816670119024936
swTranslation(1) = 0.150992701094694981
swTranslation(2) = -0.1989349410390717221
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.5043163446909643133
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.6679670555810516275
swTranslation(1) = 0.1926163718008373216
swTranslation(2) = -0.2396806518543033171
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.4202636205758036314
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.563302793231123422
swTranslation(1) = 0.160513643167364467
swTranslation(2) = -0.199733876545252792
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.3502196838131697021
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.4760825746061830843
swTranslation(1) = 0.1337613693061371622
swTranslation(2) = -0.1664448971210439332
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.2918497365109747888
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.4033990590853995806
swTranslation(1) = 0.1114678077551142371
swTranslation(2) = -0.1387040809342033054
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.351626188567439546
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.4529581571421593122
swTranslation(1) = 0.1305629444171390041
swTranslation(2) = -0.1671133505231365002
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.2930218238061996217
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.3841287111987130021
swTranslation(1) = 0.10880245368094911
swTranslation(2) = -0.1392611254359470974
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.2441848531718330273
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.3267708395791744103
swTranslation(1) = 0.09066871140079089952
swTranslation(2) = -0.1160509378632892247
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.2034873776431942172
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.2789726132295588523
swTranslation(1) = 0.07555725950065912688
swTranslation(2) = -0.09670911488607440709
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.2451655152327641418
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.3184986557763540005
swTranslation(1) = 0.07303395053626926536
swTranslation(2) = -0.116517005886836611
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.2953801388346555812
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.3692617098822649213
swTranslation(1) = 0.07483314405306873418
swTranslation(2) = -0.1403819348034175962
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector

' Zoom In/Out (MouseWheel)
Set swModelView = Part.ActiveView
swModelView.Scale2 = 0.3558796853429585516
ReDim swTranslation(0 To 2) As Double
swTranslation(0) = 0.4300824142936702787
swTranslation(1) = 0.07793475187116703784
swTranslation(2) = -0.169134861208936893
swTranslationVar = swTranslation
Set swMathUtils = swApp.GetMathUtility()
Set swTranslationVector = swMathUtils.CreateVector((swTranslationVar))
swModelView.Translation3 = swTranslationVector
Part.ClearSelection2 True
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.02036217460660055475, 0.1192806015118321739, 0.1145851962862707296, 1.513992326566324209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.05242922839103508065, -0.2239839206726061127, 0.1192806015118321739, 0.1145851962862707296, 1.513992326566324209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, -0.05090543651650138862, 0.1192806015118321739, 0.1145851962862707296, 1.513992326566324209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.008738204731839178951, -0.04072434921320110951, 0.1192806015118321739, 0.1145851962862707296, 1.513992326566324209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint -0.004369102365919589476, -0.03054326190990083387, 0.1192806015118321739, 0.1145851962862707296, 1.513992326566324209
Set myModelView = Part.ActiveView
myModelView.RotateAboutPoint 0, -0.01018108730330027738, 0.1192806015118321739, 0.1145851962862707296, 1.513992326566324209

' Roll View
Set swModelView = Part.ActiveView
swModelView.RollBy 0
swApp.ExitApp
End Sub
